export enum ActionType {
    GET_EVENTS = 'get_events',
    GET_EVENTS_SUCCESS = 'get_events_success',
    GET_EVENTS_ERROR = 'get_events_error',
    GET_GENRES = 'get_genres',
    GET_GENRES_SUCCESS = 'get_genres__success',
    GET_GENRES_ERROR = 'get_genres_error',
    GET_METRO_AREAS = 'get_metro_areas',
    GET_METRO_AREAS_SUCCESS = 'get_metro_areas_success',
    GET_METRO_AREAS_ERROR = 'get_metro_areas_error',
    SET_GENRE = 'set_genre',
    SET_GENRE_SUCCESS = 'set_genre_success',
    SET_GENRE_ERROR = 'set_genre_error',
    SET_METRO_AREA = 'set_metro_area',
    SET_METRO_AREA_SUCCESS = 'set_metro_area_success',
    SET_METRO_AREA_ERROR = 'set_metro_area_error',
}
