name: Workflow Test

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}