name: Workflow Test

on:
  push:
    branches:
      - feature/github-actions

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Log Repo
        run: |
          echo $GITHUB_REPOSITORY